INSERT INTO hobbies (hobby) VALUES ('Drawing');
INSERT INTO hobbies (hobby) VALUES ('Painting');
INSERT INTO hobbies (hobby) VALUES ('Creative Writing');
INSERT INTO hobbies (hobby) VALUES ('Sculpting');
INSERT INTO hobbies (hobby) VALUES ('Photography');
INSERT INTO hobbies (hobby) VALUES ('Gardening');
INSERT INTO hobbies (hobby) VALUES ('Dancing');
INSERT INTO hobbies (hobby) VALUES ('Pottery');
INSERT INTO hobbies (hobby) VALUES ('Woodworking');
INSERT INTO hobbies (hobby) VALUES ('Baking');
INSERT INTO hobbies (hobby) VALUES ('Flower Arranging');
INSERT INTO hobbies (hobby) VALUES ('Graphic Design');
INSERT INTO hobbies (hobby) VALUES ('Model Building');
INSERT INTO hobbies (hobby) VALUES ('Piano');
INSERT INTO hobbies (hobby) VALUES ('Cooking');
INSERT INTO hobbies (hobby) VALUES ('Nail Art');
INSERT INTO hobbies (hobby) VALUES ('Origami');
INSERT INTO hobbies (hobby) VALUES ('Puzzles');
INSERT INTO hobbies (hobby) VALUES ('Scrapbooking');
INSERT INTO hobbies (hobby) VALUES ('Collecting');
INSERT INTO hobbies (hobby) VALUES ('Sewing');
INSERT INTO hobbies (hobby) VALUES ('Weightlifting');
INSERT INTO hobbies (hobby) VALUES ('3D Printing');
INSERT INTO hobbies (hobby) VALUES ('Beatboxing');
INSERT INTO hobbies (hobby) VALUES ('Coding');
INSERT INTO hobbies (hobby) VALUES ('Weaving');
INSERT INTO hobbies (hobby) VALUES ('Knitting');
INSERT INTO hobbies (hobby) VALUES ('Singing');
INSERT INTO hobbies (hobby) VALUES ('Meditation');
INSERT INTO hobbies (hobby) VALUES ('Landscaping');
INSERT INTO hobbies (hobby) VALUES ('Running');
INSERT INTO hobbies (hobby) VALUES ('Mountain Biking');
INSERT INTO hobbies (hobby) VALUES ('Skiing/Snowboarding');
INSERT INTO hobbies (hobby) VALUES ('Hiking');
INSERT INTO hobbies (hobby) VALUES ('Climbing');
INSERT INTO hobbies (hobby) VALUES ('Basketball');
INSERT INTO hobbies (hobby) VALUES ('Camping');
INSERT INTO hobbies (hobby) VALUES ('Backpacking');
INSERT INTO hobbies (hobby) VALUES ('Mountaineering');
INSERT INTO hobbies (hobby) VALUES ('Go Karting');
INSERT INTO hobbies (hobby) VALUES ('Paintball');

INSERT INTO tv_shows (show) VALUES ('Friends');
INSERT INTO tv_shows (show) VALUES ('Succession');
INSERT INTO tv_shows (show) VALUES ('The Office');
INSERT INTO tv_shows (show) VALUES ('Breaking Bad');
INSERT INTO tv_shows (show) VALUES ('Modern Family');
INSERT INTO tv_shows (show) VALUES ('Stranger Things');
INSERT INTO tv_shows (show) VALUES ('Big Little Lies');
INSERT INTO tv_shows (show) VALUES ('Gilmore Girls');
INSERT INTO tv_shows (show) VALUES ('Ozark');
INSERT INTO tv_shows (show) VALUES ('Severance');
INSERT INTO tv_shows (show) VALUES ('Mr. Robot');
INSERT INTO tv_shows (show) VALUES ('Black Mirror');
INSERT INTO tv_shows (show) VALUES ('Arrested Development');
INSERT INTO tv_shows (show) VALUES ('Reno 911');
INSERT INTO tv_shows (show) VALUES ('Too Hot to Handle');
INSERT INTO tv_shows (show) VALUES ('Shameless');
INSERT INTO tv_shows (show) VALUES ('Love Island');
INSERT INTO tv_shows (show) VALUES ('Jane the Virgin');
INSERT INTO tv_shows (show) VALUES ('Outer Banks');
INSERT INTO tv_shows (show) VALUES ('Narcos');
INSERT INTO tv_shows (show) VALUES ('Orange is the New Black');
INSERT INTO tv_shows (show) VALUES ('Full House');
INSERT INTO tv_shows (show) VALUES ('Gossip Girl');
INSERT INTO tv_shows (show) VALUES ('Greys Anatomy');

INSERT INTO movies (movie) VALUES ('Saving Private Ryan');
INSERT INTO movies (movie) VALUES ('Good Will Hunting');
INSERT INTO movies (movie) VALUES ('Parasite');
INSERT INTO movies (movie) VALUES ('Dead Poets Society');
INSERT INTO movies (movie) VALUES ('Forrest Gump');
INSERT INTO movies (movie) VALUES ('The Avengers');
INSERT INTO movies (movie) VALUES ('Marvel');
INSERT INTO movies (movie) VALUES ('La La Land');
INSERT INTO movies (movie) VALUES ('Star Wars');
INSERT INTO movies (movie) VALUES ('Avatar');
INSERT INTO movies (movie) VALUES ('Top Gun');
INSERT INTO movies (movie) VALUES ('Titanic');
INSERT INTO movies (movie) VALUES ('Jurassic World');
INSERT INTO movies (movie) VALUES ('Incredibles');
INSERT INTO movies (movie) VALUES ('The Lion King');
INSERT INTO movies (movie) VALUES ('Hunger Games');
INSERT INTO movies (movie) VALUES ('Harry Potter');
INSERT INTO movies (movie) VALUES ('Despicable Me');
INSERT INTO movies (movie) VALUES ('American Sniper');
INSERT INTO movies (movie) VALUES ('Pirates of the Caribbean');
INSERT INTO movies (movie) VALUES ('Twilight');

INSERT INTO artists (artist) VALUES ('The Beatles');
INSERT INTO artists (artist) VALUES ('Beyonce');
INSERT INTO artists (artist) VALUES ('Michael Jackson');
INSERT INTO artists (artist) VALUES ('Madonna');
INSERT INTO artists (artist) VALUES ('Miley Cyrus');
INSERT INTO artists (artist) VALUES ('Justin Bieber');
INSERT INTO artists (artist) VALUES ('Taylor Swift');
INSERT INTO artists (artist) VALUES ('The Spice Girls');
INSERT INTO artists (artist) VALUES ('Lady Gaga');
INSERT INTO artists (artist) VALUES ('The Beach Boys');
INSERT INTO artists (artist) VALUES ('Katy Perry');
INSERT INTO artists (artist) VALUES ('Rolling Stones');
INSERT INTO artists (artist) VALUES ('Noah Kahan');
INSERT INTO artists (artist) VALUES ('ABBA');
INSERT INTO artists (artist) VALUES ('Coldplay');
INSERT INTO artists (artist) VALUES ('blink-182');
INSERT INTO artists (artist) VALUES ('Carrie Underwood');
INSERT INTO artists (artist) VALUES ('Drake');
INSERT INTO artists (artist) VALUES ('Eminem');
INSERT INTO artists (artist) VALUES ('Kanye West');
INSERT INTO artists (artist) VALUES ('Fetty Wap');
INSERT INTO artists (artist) VALUES ('Jay-Z');
INSERT INTO artists (artist) VALUES ('Tupac');
INSERT INTO artists (artist) VALUES ('Harry Styles');
INSERT INTO artists (artist) VALUES ('Kendrick Lamar');
INSERT INTO artists (artist) VALUES ('Lil Uzi Vert');
INSERT INTO artists (artist) VALUES ('Mariah Carey');
INSERT INTO artists (artist) VALUES ('Mac Miller');
INSERT INTO artists (artist) VALUES ('OneRepublic');
INSERT INTO artists (artist) VALUES ('Imagine Dragons');
INSERT INTO artists (artist) VALUES ('Pitbull');
INSERT INTO artists (artist) VALUES ('Queen');
INSERT INTO artists (artist) VALUES ('Snoopdogg');
INSERT INTO artists (artist) VALUES ('Yoke Lore');

INSERT INTO majors (major) VALUES ('Computer Science');
INSERT INTO majors (major) VALUES ('Psychology');
INSERT INTO majors (major) VALUES ('Mathematics');
INSERT INTO majors (major) VALUES ('Biology');
INSERT INTO majors (major) VALUES ('Engineering');
INSERT INTO majors (major) VALUES ('Economics');
INSERT INTO majors (major) VALUES ('Accounting');
INSERT INTO majors (major) VALUES ('Political science');
INSERT INTO majors (major) VALUES ('Business');
INSERT INTO majors (major) VALUES ('Physics');
INSERT INTO majors (major) VALUES ('Finance');
INSERT INTO majors (major) VALUES ('Mechanical Engineering');
INSERT INTO majors (major) VALUES ('Chemical Engineering');
INSERT INTO majors (major) VALUES ('Marketing');
INSERT INTO majors (major) VALUES ('Communications');
INSERT INTO majors (major) VALUES ('Electrical engineering');
INSERT INTO majors (major) VALUES ('Nursing');
INSERT INTO majors (major) VALUES ('Chemistry');
INSERT INTO majors (major) VALUES ('Computer Engineering');
INSERT INTO majors (major) VALUES ('Business administration');
INSERT INTO majors (major) VALUES ('Biomedical engineering');
INSERT INTO majors (major) VALUES ('Information technology');
INSERT INTO majors (major) VALUES ('Social science');
INSERT INTO majors (major) VALUES ('Civil Engineering');
INSERT INTO majors (major) VALUES ('Animal science');
INSERT INTO majors (major) VALUES ('Sports science');
INSERT INTO majors (major) VALUES ('Biochemistry');
INSERT INTO majors (major) VALUES ('Sports marketing');
INSERT INTO majors (major) VALUES ('N/A');

INSERT INTO jobs (job) VALUES ('Software Developer');
INSERT INTO jobs (job) VALUES ('Psychiatrist');
INSERT INTO jobs (job) VALUES ('Surgeon');
INSERT INTO jobs (job) VALUES ('Anesthesiologist');
INSERT INTO jobs (job) VALUES ('Lawyer');
INSERT INTO jobs (job) VALUES ('Dentist');
INSERT INTO jobs (job) VALUES ('Nurse Anesthetist');
INSERT INTO jobs (job) VALUES ('Physician assistant');
INSERT INTO jobs (job) VALUES ('Financial Manager');
INSERT INTO jobs (job) VALUES ('Sales Management');
INSERT INTO jobs (job) VALUES ('Chief Executive Officer');
INSERT INTO jobs (job) VALUES ('Nurse Practitioner');
INSERT INTO jobs (job) VALUES ('Engineer');
INSERT INTO jobs (job) VALUES ('Registered Nurse');
INSERT INTO jobs (job) VALUES ('Aircraft pilot');
INSERT INTO jobs (job) VALUES ('Independent Contractor');
INSERT INTO jobs (job) VALUES ('Tutor');
INSERT INTO jobs (job) VALUES ('Bartender');
INSERT INTO jobs (job) VALUES ('Waiter');
INSERT INTO jobs (job) VALUES ('Customer service representative');
INSERT INTO jobs (job) VALUES ('Receptionist');
INSERT INTO jobs (job) VALUES ('Graphic Designer');
INSERT INTO jobs (job) VALUES ('Babysitter');
INSERT INTO jobs (job) VALUES ('Administrative assistant');
INSERT INTO jobs (job) VALUES ('Virtual assistant');
INSERT INTO jobs (job) VALUES ('Dental hygienist');
INSERT INTO jobs (job) VALUES ('Personal trainer');
INSERT INTO jobs (job) VALUES ('Photographer');
INSERT INTO jobs (job) VALUES ('Tour guide');
INSERT INTO jobs (job) VALUES ('Security Officer');
INSERT INTO jobs (job) VALUES ('Real Estate Agent');
INSERT INTO jobs (job) VALUES ('Bank teller');
INSERT INTO jobs (job) VALUES ('Delivery driver');
INSERT INTO jobs (job) VALUES ('Physiotherapist');
INSERT INTO jobs (job) VALUES ('Occupational Therapist');
INSERT INTO jobs (job) VALUES ('Mail carrier');
INSERT INTO jobs (job) VALUES ('Warehouse worker');
INSERT INTO jobs (job) VALUES ('N/A');