INSERT INTO hobbies (hobby) VALUES ('Drawing');
INSERT INTO hobbies (hobby) VALUES ('Painting');
INSERT INTO hobbies (hobby) VALUES ('Creative Writing');
INSERT INTO hobbies (hobby) VALUES ('Sculpting');
INSERT INTO hobbies (hobby) VALUES ('Photography');
INSERT INTO hobbies (hobby) VALUES ('Gardening');
INSERT INTO hobbies (hobby) VALUES ('Dancing');
INSERT INTO hobbies (hobby) VALUES ('Pottery');
INSERT INTO hobbies (hobby) VALUES ('Woodworking');
INSERT INTO hobbies (hobby) VALUES ('Baking');
INSERT INTO hobbies (hobby) VALUES ('Flower Arranging');
INSERT INTO hobbies (hobby) VALUES ('Graphic Design');
INSERT INTO hobbies (hobby) VALUES ('Model Building');
INSERT INTO hobbies (hobby) VALUES ('Piano');
INSERT INTO hobbies (hobby) VALUES ('Cooking');
INSERT INTO hobbies (hobby) VALUES ('Nail Art');
INSERT INTO hobbies (hobby) VALUES ('Origami');
INSERT INTO hobbies (hobby) VALUES ('Puzzles');
INSERT INTO hobbies (hobby) VALUES ('Scrapbooking');
INSERT INTO hobbies (hobby) VALUES ('Collecting');
INSERT INTO hobbies (hobby) VALUES ('Sewing');
INSERT INTO hobbies (hobby) VALUES ('Weightlifting');
INSERT INTO hobbies (hobby) VALUES ('3D Printing');
INSERT INTO hobbies (hobby) VALUES ('Beatboxing');
INSERT INTO hobbies (hobby) VALUES ('Coding');
INSERT INTO hobbies (hobby) VALUES ('Weaving');
INSERT INTO hobbies (hobby) VALUES ('Knitting');
INSERT INTO hobbies (hobby) VALUES ('Singing');
INSERT INTO hobbies (hobby) VALUES ('Meditation');
INSERT INTO hobbies (hobby) VALUES ('Landscaping');
INSERT INTO hobbies (hobby) VALUES ('Running');
INSERT INTO hobbies (hobby) VALUES ('Mountain Biking');
INSERT INTO hobbies (hobby) VALUES ('Skiing/Snowboarding');
INSERT INTO hobbies (hobby) VALUES ('Hiking');
INSERT INTO hobbies (hobby) VALUES ('Climbing');
INSERT INTO hobbies (hobby) VALUES ('Basketball');
INSERT INTO hobbies (hobby) VALUES ('Camping');
INSERT INTO hobbies (hobby) VALUES ('Backpacking');
INSERT INTO hobbies (hobby) VALUES ('Mountaineering');
INSERT INTO hobbies (hobby) VALUES ('Go Karting');
INSERT INTO hobbies (hobby) VALUES ('Paintball');

INSERT INTO tv_shows (show) VALUES ('Friends');
INSERT INTO tv_shows (show) VALUES ('Succession');
INSERT INTO tv_shows (show) VALUES ('The Office');
INSERT INTO tv_shows (show) VALUES ('Breaking Bad');
INSERT INTO tv_shows (show) VALUES ('Modern Family');
INSERT INTO tv_shows (show) VALUES ('Stranger Things');
INSERT INTO tv_shows (show) VALUES ('Big Little Lies');
INSERT INTO tv_shows (show) VALUES ('Gilmore Girls');
INSERT INTO tv_shows (show) VALUES ('Ozark');
INSERT INTO tv_shows (show) VALUES ('Severance');
INSERT INTO tv_shows (show) VALUES ('Mr. Robot');
INSERT INTO tv_shows (show) VALUES ('Black Mirror');
INSERT INTO tv_shows (show) VALUES ('Arrested Development');
INSERT INTO tv_shows (show) VALUES ('Reno 911');
INSERT INTO tv_shows (show) VALUES ('Too Hot to Handle');
INSERT INTO tv_shows (show) VALUES ('Shameless');
INSERT INTO tv_shows (show) VALUES ('Love Island');
INSERT INTO tv_shows (show) VALUES ('Jane the Virgin');
INSERT INTO tv_shows (show) VALUES ('Outer Banks');
INSERT INTO tv_shows (show) VALUES ('Narcos');
INSERT INTO tv_shows (show) VALUES ('Orange is the New Black');
INSERT INTO tv_shows (show) VALUES ('Full House');
INSERT INTO tv_shows (show) VALUES ('Gossip Girl');
INSERT INTO tv_shows (show) VALUES ('Greys Anatomy');

INSERT INTO movies (movie) VALUES ('Saving Private Ryan');
INSERT INTO movies (movie) VALUES ('Good Will Hunting');
INSERT INTO movies (movie) VALUES ('Parasite');
INSERT INTO movies (movie) VALUES ('Dead Poets Society');
INSERT INTO movies (movie) VALUES ('Forrest Gump');
INSERT INTO movies (movie) VALUES ('The Avengers');
INSERT INTO movies (movie) VALUES ('Marvel');
INSERT INTO movies (movie) VALUES ('La La Land');
INSERT INTO movies (movie) VALUES ('Star Wars');
INSERT INTO movies (movie) VALUES ('Avatar');
INSERT INTO movies (movie) VALUES ('Top Gun');
INSERT INTO movies (movie) VALUES ('Titanic');
INSERT INTO movies (movie) VALUES ('Jurassic World');
INSERT INTO movies (movie) VALUES ('Incredibles');
INSERT INTO movies (movie) VALUES ('The Lion King');
INSERT INTO movies (movie) VALUES ('Hunger Games');
INSERT INTO movies (movie) VALUES ('Harry Potter');
INSERT INTO movies (movie) VALUES ('Despicable Me');
INSERT INTO movies (movie) VALUES ('American Sniper');
INSERT INTO movies (movie) VALUES ('Pirates of the Caribbean');
INSERT INTO movies (movie) VALUES ('Twilight');

INSERT INTO artists (artist) VALUES ('The Beatles');
INSERT INTO artists (artist) VALUES ('Beyonce');
INSERT INTO artists (artist) VALUES ('Michael Jackson');
INSERT INTO artists (artist) VALUES ('Madonna');
INSERT INTO artists (artist) VALUES ('Miley Cyrus');
INSERT INTO artists (artist) VALUES ('Justin Bieber');
INSERT INTO artists (artist) VALUES ('Taylor Swift');
INSERT INTO artists (artist) VALUES ('The Spice Girls');
INSERT INTO artists (artist) VALUES ('Lady Gaga');
INSERT INTO artists (artist) VALUES ('The Beach Boys');
INSERT INTO artists (artist) VALUES ('Katy Perry');
INSERT INTO artists (artist) VALUES ('Rolling Stones');
INSERT INTO artists (artist) VALUES ('Noah Kahan');
INSERT INTO artists (artist) VALUES ('ABBA');
INSERT INTO artists (artist) VALUES ('Coldplay');
INSERT INTO artists (artist) VALUES ('blink-182');
INSERT INTO artists (artist) VALUES ('Carrie Underwood');
INSERT INTO artists (artist) VALUES ('Drake');
INSERT INTO artists (artist) VALUES ('Eminem');
INSERT INTO artists (artist) VALUES ('Kanye West');
INSERT INTO artists (artist) VALUES ('Fetty Wap');
INSERT INTO artists (artist) VALUES ('Jay-Z');
INSERT INTO artists (artist) VALUES ('Tupac');
INSERT INTO artists (artist) VALUES ('Harry Styles');
INSERT INTO artists (artist) VALUES ('Kendrick Lamar');
INSERT INTO artists (artist) VALUES ('Lil Uzi Vert');
INSERT INTO artists (artist) VALUES ('Mariah Carey');
INSERT INTO artists (artist) VALUES ('Mac Miller');
INSERT INTO artists (artist) VALUES ('OneRepublic');
INSERT INTO artists (artist) VALUES ('Imagine Dragons');
INSERT INTO artists (artist) VALUES ('Pitbull');
INSERT INTO artists (artist) VALUES ('Queen');
INSERT INTO artists (artist) VALUES ('Snoopdogg');
INSERT INTO artists (artist) VALUES ('Yoke Lore');
